/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
        TestCases tests = new TestCases(); // Initialize your test class
        // SearchAmazon search = new SearchAmazon();
        // Countlinks countlinks = new Countlinks();
        // Linkedln  lk = new Linkedln();
        // bookmyshow bk = new bookmyshow();
        framescode fc = new framescode();

        //TODO: call your test case functions one after other here

        
        // search.testCase02();
        // countlinks.testCase03();
        // lk.testCase04();
        // bk.testCase05();
        fc.testCase06();


        //END Tests


        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
