/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
        TestCases tests = new TestCases(); // Initialize your test class
        // SearchAmazon search = new SearchAmazon();
        // Countlinks countlinks = new Countlinks();
        // Linkedln  lk = new Linkedln();
        // bookmyshow bk = new bookmyshow();
        // framescode fc = new framescode();
        // imdbrating im = new imdbrating();
        // WindowHandle wh = new WindowHandle();
        Alert al = new Alert();

        //TODO: call your test case functions one after other here

        
        // search.testCase02();
        // countlinks.testCase03();
        // lk.testCase04();
        // bk.testCase05();
        // fc.testCase06();
        // im.testCase07();
        // wh.testCase08();
        al.testCase09();


        //END Tests


        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException {
        new App().getGreeting();
    }
}
